version: '3.4'

services:
  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5000:80"
    extra_hosts:
      host.docker.internal: host-gateway
  sqlusers:
    environment:
      - SA_PASSWORD=Pass12345
      - ACCEPT_EULA=Y
    ports:
     - "5001:1433"